### ISSUE TITLE
Add abillity to login with username and password

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/nodebb-plugin-write-api#65] opened 2017-01-30 13:37 UTC
Not sure if I missed something, AFAIK there's currently no way a user can do something with this API, without an admin generating a token for him...
I'd like the user being able to generate a token for himself, or a way to send login credentials along with a POST/PUT/DELETE whatever request.

(Logging in via login credentials should also support the 2FA plugin if possible, by sending you a specific response, which then could be handled by the client)

Reason for this, is that I have an app written in Java, which is supposed to automatically post some sort of progress to the forum

**Comment by julianlam** [comment] 2017-01-30 13:55
Looks like a duplicate of #2

**Closed by julianlam** 2017-01-30 13:55 UTC

**Comment by julianlam** [comment] 2017-01-30 13:56
Playing nice with the 2fa plugin is a neat idea, will have to investigate how that would work...

**Comment by RoiEXLab** [comment] 2017-01-30 14:17
Since #2 is already closed - I couldn't find such an option in the user settings menu...

**Comment by julianlam** [comment] 2017-01-30 14:40
Hi @RoiEXLab -- you should be able to `POST /api/v1/users/<uid>/tokens` with a password in the request body, to generate a token. It's the only route that will allow password login.

**Comment by julianlam** [comment] 2017-01-30 14:43
README updated to reflect this change now: b713c09

**Comment by RoiEXLab** [comment] 2017-01-30 14:45
Ok, saw this part in the readme file... Is this still required? If it is it makes this password thing useless

> Must be called with an active token for that user

**Comment by RoiEXLab** [comment] 2017-01-30 15:31
@julianlam Ok tested this out... You don't need a token (would add that inside the readme as well), but every time you issue this POST request a completely new token is generated, which I'm going to delete once I finished my actions

**Comment by julianlam** [comment] 2017-01-30 15:58
@RoiEXLab Yes, that is correct. It creates a new token. You should save that token and re-use it for subsequent requests.
