### ISSUE TITLE
/api/unread crashes

### ISSUE THREAD

**Issue by LudwikJaniuk** [NodeBB/nodebb-plugin-write-api#101] opened 2018-10-04 16:54 UTC
For some reason, having this plugin enabled results in `curl <forum-url>/api/unread` crashing the server. The relevant error seems to be: `message=Can't set headers after they are sent., stack=Error: Can't set headers after they are sent.`. I'm not sure if it's an issue on its own, or just a conflict with my other plugins, but it's nevertheless weird because this plugin shouldn't meddle in the normal `/api` (or so I thought).

**Comment by julianlam** [comment] 2018-10-04 17:02
Can you report version, and: `runningLatestWriteAPI ? try v5.1.12 : try v5.2.0`?

**Comment by LudwikJaniuk** [comment] 2018-10-04 17:03
sure, sec

**Comment by julianlam** [comment] 2018-10-04 17:03
For context, write-api hooks into `middleware.authenticate` to allow access to privileged endpoints via Bearer token.

**Comment by LudwikJaniuk** [comment] 2018-10-04 17:03
Yes, I think that's the problem, I have another plugin also hooking into middleware.authenticate

**Comment by LudwikJaniuk** [comment] 2018-10-04 17:04
It's 5.1.12

**Comment by LudwikJaniuk** [comment] 2018-10-04 17:06
Think what is happening is that both plugins get their authentication handlers called in parallell, do some stuff, and then both try to send on the response object. But since my plugin sends first, when write-api tries to do it (or set some headers or whatever), it gets the crash.

**Comment by LudwikJaniuk** [comment] 2018-10-04 17:07
How should this even be handled? Seems like the `action:middleware.authenticate` handles multiple plugins using it a bit awkwardly...

**Comment by julianlam** [comment] 2018-10-04 17:09
A-ha... yes, that could pose a problem, as the hook itself is not wired up to handle more than one listener. Let me think on this...

**Comment by julianlam** [comment] 2018-10-04 17:09
Did this problem only start in v5.2.0?

**Comment by LudwikJaniuk** [comment] 2018-10-04 17:11
I'm using It's 5.1.12, so it's here at least

**Comment by julianlam** [comment] 2018-10-04 19:02
@LudwikJaniuk Yes, that would be an acceptable workaround and shouldn't impact other write API functionality.

**Comment by LudwikJaniuk** [comment] 2018-10-04 19:43
Alright. I'll probably make a fork of this repo next time I work on this then.

**Comment by LudwikJaniuk** [comment] 2018-10-09 14:38
Yep, removing the auth hook fixed the problem. I published my version under "nodebb-plugin-write-api-brfenergi" (brfenergi is the project I'm working on). I'm not sure what should be done with this issue tho; the error should ideally be fixed on the main nodebb repo. But maybe you could implement an ACP option for this plugin to enable/disable auth?

**Comment by julianlam** [comment] 2018-10-12 19:21
> The optimal would be if the hook called its listeners serially, only continuing if the previous failed to authenticate. But changing that is a hassle...

This, I think is the best possible solution. The problem is we don't really have proper handling for hooks that interact with express' `res` for sending responses back to the client.

* **action** hooks fire all at once and don't wait for callback
* **filter** hooks call plugins sequentially and plugins mutate the passed-in parameters for later processing by core
* **static** hooks are called all at once but do not resolve until all callbacks have been called

None of those work for this use case. Filter comes close, but to get it working in the scenario you'd need to also pass in some sort of `callbackCalled` bool that plugins have to change if they invoke `res.send` or similar.

... except you can't trust plugin authors to do that sort of thing :trollface: 

----

So the solution here is to introduce a fourth type of plugin hook... one that calls handlers sequentially (like filter hooks), but checks after each one to ensure that [`res.headersSent`](http://expressjs.com/en/api.html#res.headersSent) is false. If it is true, then the final callback is called next and all interim handlers are skipped.

Now I just have to come up with a name for this type of hook :thinking: got any ideas?

**Comment by LudwikJaniuk** [comment] 2018-10-12 19:50
Mhm, "response hooks" is catchy, I think that's a good name. Yeah I figured it would have to be a version-breaking change, which I don't feel like waiting around for. But good that it's coming!

**Comment by LudwikJaniuk** [comment] 2019-01-16 14:50
@julianlam Did this by any chance get fixed since october?

**Comment by LudwikJaniuk** [comment] 2019-01-16 14:51
@julianlam Did this by any chance get fixed since October?

**Comment by julianlam** [comment] 2019-01-17 15:35
Not yet. I'm very hesitant to add a new hook type because of the implications of increased overhead. I mean, we have three types of hooks and I still have to refer back to the code every once in awhile to refamiliarise myself with how they work.

I keep flipflopping on whether it is a good idea. In fact, writing this reply, I've changed my mind twice already. The email notification for this issue is still unread in my inbox, so it is on my mind!

**Comment by julianlam** [comment] 2019-01-19 16:09
I think at this point I am fairly committed to adding the response hook. I should be able to get around to it this week :smile: 

If not, hold me accountable and keep pinging me here! :no_mouth:

**Comment by LudwikJaniuk** [comment] 2019-01-19 17:48
Awesome, thanks! I'll try ;)

**Comment by julianlam** [comment] 2019-01-19 17:49
:soon:

**Closed** 2019-01-19 19:52 UTC

**Comment by julianlam** [comment] 2019-01-19 20:03
Documentation updated as well.

**Comment by LudwikJaniuk** [comment] 2019-01-19 20:35
That's the best kind of "done within a week" that I know ;)
